# SwiftLint Configuration for Lockman
# https://github.com/realm/SwiftLint

# Included directories
included:
  - Sources
  - Tests

# Excluded directories and files
excluded:
  - .build
  - Package.swift
  - Package@swift-6.0.swift
  - Sources/Lockman/Core/Internal/Logger.swift  # 複雑な条件付きコンパイル構文のため除外
  # - Sources/**/Generated/**              # 自動生成ファイル用（必要に応じて）
  # - Sources/**/External/**               # 外部ライブラリ用（必要に応じて）

# Disabled rules
disabled_rules:
  - trailing_whitespace  # swift-formatに任せる
  - line_length         # swift-formatに任せる
  - vertical_whitespace # swift-formatに任せる
  - trailing_comma      # プロジェクトで末尾カンマを許可する場合
  - comment_spacing     # コメントスタイルを柔軟にする場合
  - sorted_imports      # swift-formatに任せる

# Enabled rules (opt-in)
opt_in_rules:
  - empty_count
  - explicit_init
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - private_over_fileprivate
  - redundant_nil_coalescing
  - switch_case_alignment
  - unneeded_parentheses_in_closure_argument
  - unused_import

# Custom rule configurations
type_name:
  min_length: 1  # 'I' のような短い型名を許可
  max_length: 40
  excluded:
    - "ID"
    - "URL"
    - "I"     # ジェネリック型パラメータなど短い名前を明示的に許可

identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - "id"
    - "url"
    - "i"
    - "j"
    - "x"
    - "y"

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

# Severity levels
force_cast: error
force_try: error
force_unwrapping: warning

# Custom rules
custom_rules:
  # Lockman specific rules
  lockman_action_id_naming:
    name: "Lockman ActionId Naming"
    regex: "struct\\s+\\w*ActionId(?!\\s*:)"
    message: "ActionId types should conform to LockmanActionId protocol"
    severity: warning