name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue with Lockman!
        
        Before submitting, please review our documentation and existing issues to see if your problem has already been addressed.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of the bug.
        Please include what version of Lockman you're using and what version introduced the issue if known.
      placeholder: |
        When using Lockman version X.Y.Z, I encountered...
        This issue started appearing after upgrading from version A.B.C.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please go through this checklist before submitting.
      options:
        - label: I have reproduced this issue using the latest version of Lockman
          required: false
        - label: I have reproduced this issue using the latest version of The Composable Architecture
          required: false
        - label: I have searched for existing issues that describe this problem
          required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened? Include any error messages or unexpected outputs.
      placeholder: |
        Error messages, unexpected behavior, etc.
        
        You can paste code snippets, logs, or terminal output here.
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: |
        Please provide a minimal reproducible example that demonstrates the issue.
        
        **⚠️ Issues without reproduction steps or code samples may be closed.**
        
        You can:
        - Provide a code snippet that reproduces the issue
        - Link to a sample project
        - Describe the exact steps to reproduce the issue
      placeholder: |
        1. Configure Lockman with...
        2. Trigger action...
        3. Observe error...
        
        ```swift
        // Minimal code example
        ```
    validations:
      required: true

  - type: input
    id: lockman-version
    attributes:
      label: Lockman version
      description: What version of Lockman are you using?
      placeholder: "0.11.0"
    validations:
      required: true

  - type: input
    id: tca-version
    attributes:
      label: The Composable Architecture version
      description: What version of TCA are you using?
      placeholder: "1.19.1"
    validations:
      required: true

  - type: input
    id: swift-version
    attributes:
      label: Swift version
      description: What version of Swift are you using?
      placeholder: "6.0"
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are affected?
      multiple: true
      options:
        - iOS
        - macOS
        - tvOS
        - watchOS
        - Mac Catalyst
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false