name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  swift-test:
    name: Test (Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            swift: '6.0'
            xcode: '16.2'
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  library-evolution:
    name: Library evolution
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.4
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build for library evolution
        run: make build-for-library-evolution

  benchmarks:
    name: Benchmarks
    runs-on: macOS-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Build benchmarks
        working-directory: Benchmarks
        run: |
          swift package resolve
          swift build -c release

  examples:
    name: Examples
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        platform: ['iOS', 'macOS']
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Build examples
        run: |
          xcodebuild build \
            -workspace Lockman.xcworkspace \
            -scheme "Strategies (${{ matrix.platform }})" \
            -destination "$(if [ "${{ matrix.platform }}" = "iOS" ]; then echo "platform=iOS Simulator,name=iPhone 15 Pro"; else echo "platform=macOS"; fi)"