name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  swift-test:
    name: Test (Swift ${{ matrix.swift }}, Xcode ${{ matrix.xcode }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest environment
          - os: macos-15
            swift: '6.0'
            xcode: '16.2'
          # Stable environment
          - os: macos-14
            swift: '5.10'
            xcode: '15.4'
          - os: macos-14
            swift: '5.9'
            xcode: '15.2'
    steps:
      - uses: actions/checkout@v4
      - name: Cache Swift dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-swift-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-${{ matrix.swift }}-
            ${{ runner.os }}-swift-
      - name: Select Xcode ${{ matrix.xcode }}
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  platform-test:
    name: Platform Test (${{ matrix.platform }}, Xcode ${{ matrix.xcode }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # iOS tests
          - os: macos-15
            xcode: '16.2'
            platform: 'iOS'
            destination: 'platform=iOS Simulator,name=iPhone 16 Pro'
          - os: macos-14
            xcode: '15.2'
            platform: 'iOS'
            destination: 'platform=iOS Simulator,name=iPhone 15 Pro'
          # macOS tests
          - os: macos-15
            xcode: '16.2'
            platform: 'macOS'
            destination: 'platform=macOS'
          - os: macos-14
            xcode: '15.2'
            platform: 'macOS'
            destination: 'platform=macOS'
          # tvOS tests
          - os: macos-15
            xcode: '16.2'
            platform: 'tvOS'
            destination: 'platform=tvOS Simulator,name=Apple TV'
          - os: macos-14
            xcode: '15.2'
            platform: 'tvOS'
            destination: 'platform=tvOS Simulator,name=Apple TV'
          # watchOS tests
          - os: macos-15
            xcode: '16.2'
            platform: 'watchOS'
            destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
          - os: macos-14
            xcode: '15.2'
            platform: 'watchOS'
            destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
          # Mac Catalyst
          - os: macos-15
            xcode: '16.2'
            platform: 'Mac Catalyst'
            destination: 'platform=macOS,variant=Mac Catalyst'
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build/DerivedData
          key: ${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ matrix.platform }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ matrix.platform }}-
            ${{ runner.os }}-xcode-${{ matrix.xcode }}-
      - name: Build and test for ${{ matrix.platform }}
        run: |
          xcodebuild test \
            -scheme LockmanCore \
            -destination "${{ matrix.destination }}" \
            -derivedDataPath .build/DerivedData \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            | xcbeautify || true

  library-evolution:
    name: Library evolution
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Cache Swift dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-lib-evolution-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-lib-evolution-
      - name: Select Xcode 15.4
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build for library evolution
        run: make build-for-library-evolution

  benchmarks:
    name: Benchmarks
    runs-on: macOS-15
    steps:
      - uses: actions/checkout@v4
      - name: Cache Swift dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build
            Benchmarks/.build
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-benchmarks-${{ hashFiles('**/Package.resolved', 'Benchmarks/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-benchmarks-
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Build benchmarks
        working-directory: Benchmarks
        run: |
          make benchmarks

  examples:
    name: Examples
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build/DerivedData
          key: ${{ runner.os }}-xcode-examples-${{ hashFiles('**/Package.resolved', 'Examples/**/*.xcodeproj/project.pbxproj') }}
          restore-keys: |
            ${{ runner.os }}-xcode-examples-
            ${{ runner.os }}-xcode-
      - name: Select Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Build examples for iOS
        run: |
          xcodebuild build \
            -workspace Lockman.xcworkspace \
            -scheme "Strategies" \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro" \
            -derivedDataPath .build/DerivedData \
            -skipMacroValidation \
            -skipPackagePluginValidation
      - name: Build examples for macOS
        run: |
          xcodebuild build \
            -workspace Lockman.xcworkspace \
            -scheme "Strategies" \
            -destination "platform=macOS" \
            -derivedDataPath .build/DerivedData \
            -skipMacroValidation \
            -skipPackagePluginValidation