name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    types: [ready_for_review]
    branches:
      - main
      - develop
      - 'feature/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  swift-test:
    name: Swift Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos-14, xcode: '15.4' }
          - { os: macos-15, xcode: '16.0' }
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      
      - name: Swift version
        run: swift --version
      
      - name: Build
        run: swift build
      
      - name: Run tests
        run: swift test --parallel

  xcodebuild:
    name: Build (${{ matrix.platform }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ['iOS', 'macOS', 'tvOS', 'watchOS']

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Set platform variables
        id: platform
        run: |
          case "${{ matrix.platform }}" in
            "iOS")
              echo "destination=generic/platform=iOS" >> $GITHUB_OUTPUT
              ;;
            "macOS")
              echo "destination=generic/platform=macOS" >> $GITHUB_OUTPUT
              ;;
            "tvOS")
              echo "destination=generic/platform=tvOS" >> $GITHUB_OUTPUT
              ;;
            "watchOS")
              echo "destination=generic/platform=watchOS" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Build with Swift
        run: |
          case "${{ matrix.platform }}" in
            "iOS")
              swift build --sdk iphoneos
              ;;
            "macOS")
              swift build
              ;;
            "tvOS")
              swift build --sdk appletvos
              ;;
            "watchOS")
              swift build --sdk watchos
              ;;
          esac

  examples:
    name: Examples
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Build Strategies Example
        run: |
          cd Examples/Strategies
          xcodebuild build \
            -project Strategies.xcodeproj \
            -scheme Strategies \
            -configuration Debug \
            -destination "platform=macOS" \
            CODE_SIGNING_ALLOWED=NO

  benchmarks:
    name: Benchmarks
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      
      - name: Install dependencies
        run: brew install jemalloc
      
      - name: Run benchmarks
        run: |
          cd Benchmarks
          swift package resolve
          swift build -c release
          swift package benchmark --target LockmanBenchmarks

  check-macro-compatibility:
    name: Check Macro Compatibility
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Select latest Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Check macro compatibility
        run: |
          swift package diagnose-api-breaking-changes 1.17.1 || true