name: Format

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      
      - name: Install swift-format
        run: |
          git clone https://github.com/apple/swift-format.git
          cd swift-format
          git checkout release/6.0
          swift build -c release
          sudo cp .build/release/swift-format /usr/local/bin/
      
      - name: Format
        run: make format
      
      - name: Check for changes
        id: git-check
        run: |
          if git diff --exit-code; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.git-check.outputs.changes == 'true'
        with:
          commit_message: "chore: run swift-format [skip ci]"
          commit_options: '--no-verify'
          file_pattern: '*.swift'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>