name: Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    types: [ready_for_review]
    branches:
      - main
      - develop
      - 'feature/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        include:
          # Swift 5.9
          - os: macos-14
            swift: '5.9'
            xcode: '15.2'
          
          # Swift 6.0
          - os: macos-15
            swift: '6.0'
            xcode: '16.0'
          
          # Swift 6.1
          - os: macos-15
            swift: '6.1'
            xcode: '16.1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Swift version
        run: swift --version

      - name: Cache Swift PM
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ matrix.swift }}-
            ${{ runner.os }}-spm-

      # Build and Test all platforms
      - name: Build and Test
        run: |
          swift test --enable-code-coverage

      # Coverage
      - name: Prepare coverage reports
        run: |
          xcrun llvm-cov export \
            .build/debug/LockmanPackageTests.xctest/Contents/MacOS/LockmanPackageTests \
            -instr-profile .build/debug/codecov/default.profdata \
            -format="lcov" > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: unittests,swift${{ matrix.swift }}
          name: swift-${{ matrix.swift }}-${{ matrix.os }}
          fail_ci_if_error: true
          verbose: true

  coverage-check:
    name: Coverage Check
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          threshold: 80%